### ISSUE TITLE
[Account] As a Customer I want to Create My Account So that I Can place an order

### ISSUE THREAD

**Issue by freedomkhanyile** [freedomkhanyile/bet-ecommerce-software#2]
### Tasks

- [ ] Create User Entity

**User**
- Id
- Email
- Password
- Token [CORS]

- [ ]  Create Account Endpoint
<br>RegisterController
- Email
- Password
> Returns
**User**

- [ ] Create Account Service

<br> AccountService
- Register()

- [ ] Unit Test
